#!/bin/sh

while true; do
	BATT=$(cat /sys/class/power_supply/BAT1/capacity)
	BATTSTAT=""
	MEM=$(free -h | awk '/^Mem:/ {print $3 "/" $2}')
	TEMP=$(sensors | awk '/^temp1/ {print $2}' | awk NR==1)
	UPD="0"

	[ "$(checkupdates | wc -l)" ] && UPD=$(checkupdates | wc -l)

	[ "$(cat /sys/class/power_supply/BAT1/status)" = "Charging" ] && BATTSTAT=" ^"
	
	desktops=""
	echo "%{l} $desktops %{r} UPDT: $UPD | CPU: $TEMP | MEM: $MEM | $(date '+%D, %R') | BATT: $BATT%$BATTSTAT"

	sleep 30
done &
