#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap           2

bspc config pointer_follows_focus false
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a LibreWolf desktop='^9'
bspc rule -a qutebrowser desktop='^9'
bspc rule -a mpv desktop='^8'
# bspc rule -a MuPDF state=floating

xsetroot -cursor_name left_ptr
pgrep -x panel > /dev/null || panel &
xrdb ~/.Xresources
~/.fehbg
wmname LG3D
