#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           7

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a qutebrowser desktop='^9'
bspc rule -a mpv desktop='^8'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

i=1;for d in $(bspc query -D --names); do bspc desktop $d --rename $i;i=$[i+1]; done

pgrep -x panel > /dev/null || panel &
