#!/bin/bash

DATABASE_FILE=$KEEPASS_DATABASE_PATH
KEY_FILE=$KEYFILE_PATH
TMP_FILE=$TMP_KEEPASS_FILE
STORE_TMP_FILE=true

# MASTER_PASSWORD_COMMAND="dmenu -p \"Master password\" -nf \"#282828\""
# SELECT_ENTRY_COMMAND="dmenu -l 15 -i"

MASTER_PASSWORD_COMMAND="rofi -dmenu -l 0 -p \"Master password\" -theme-str 'entry { enabled: false;}'"
SELECT_ENTRY_COMMAND="rofi -dmenu -p \"Select entry\" -l 15 -i"

pass=$(< $TMP_FILE) \
	|| pass=$(eval $MASTER_PASSWORD_COMMAND < /dev/null) \
	|| exit 1

[[ $STORE_TMP_FILE == "true" ]] && printf "%s" $pass > $TMP_FILE

entries=$(keepassxc-cli ls -Rf -k $KEY_FILE $DATABASE_FILE <<< $pass) || { rm $TMP_FILE ; exit 1; }

entry=$(eval $SELECT_ENTRY_COMMAND <<< $entries) || exit 1

output=$(keepassxc-cli show -s -k $KEY_FILE $DATABASE_FILE $entry <<< $pass)

username=$(awk -F ':' '/^UserName/ {print $2}' <<< $output)
pass=$(awk -F ':' '/^Password/ {print $2}' <<< $output)

type_x() { [[ -n "$1" ]] && xdotool type --delay 0 $1 || exit 1 && unset $1; }
type_password() { type_x $pass; }
type_username() { type_x $username; }

[[ "u" == "$1" ]] && type_username && exit 0
[[ "p" == "$1" ]] && type_password && exit 0

type_username
xdotool key Tab || exit 1
type_password
