#!/usr/bin/sh

curl -s https://pokemon-project.com/episodios/latino/serie-ash/temporada-6 | grep -o "https://pokemon-project.com/episodios/latino/serie-ash/temporada-6/episodio-.*[0-9]\">" | sed 's/\">//' | sort -u --version-sort | dmenu -l 30 | xargs mpv
